### ISSUE TITLE
Enter your roles to RAM

### ISSUE THREAD

**Issue by mehmetburakkurutmaz** [bounswe/bounswe2015group5#124]
Enter your roles and responsibilities to our RAM spreadsheet by taking the lecture into consideration.

You can find relevant lecture notes in here:
https://d1b10bmlvqabco.cloudfront.net/attach/i5pbxkrwyq0741/i5pc4pzisje6cg/i9494saeoq8w/RAM.pdf

And link to RAM spreadsheet is here:
https://docs.google.com/spreadsheets/d/1ofm8RRBomgB_wxKT5qXeEejzWAvvk2wuxwGHu2ZJsu4/edit#gid=0

This issue will be closed, after everyone has completed his job.

**Comment by mehmetburakkurutmaz** [comment]
I have completed my part of the RAM.

**Comment by haknsahn** [comment]
I have entered my roles to RAM spreadsheet.

**Comment by mtozsahin** [comment]
I have entered my roles to RAM spreadsheet. Also assigned future roles, and roughly made a division of labor. Of course, every member have right to criticize and request for a change on their roles.

**Comment by mrtcnkrcby** [comment]
I completed my parts of the RAM

**Comment by ulusalomer** [comment]
I've entered my roles to RAM.

**Comment by yilmazelb** [comment]
I've entered my roles to RAM.

**Comment by melihdemiroren** [comment]
I've entered my roles to RAM.

**Comment by abdullahanefi** [comment]
Entered my roles
