### ISSUE TITLE
Code Review Request

### ISSUE THREAD

**Issue by moguz** [bounswe/bounswe2015group5#204]
I'd love some feedback on my commit 29df5c8b639d76fe52a74aa1ec236d3c4a8e7787 where the Contribution Detail page on Android was mainly implemented.

**Comment by haknsahn** [comment]
Commented on [the commit](https://github.com/bounswe/bounswe2015group5/commit/29df5c8b639d76fe52a74aa1ec236d3c4a8e7787) and added my review's link into [Code Review Assignment](https://github.com/bounswe/bounswe2015group5/wiki/Code-Review-Assignment) page
