### ISSUE TITLE
Code Review Request

### ISSUE THREAD

**Issue by abdullahanefi** [bounswe/bounswe2015group5#206]
I need some feedback on my [commit](https://github.com/bounswe/bounswe2015group5/commit/dcea5f680623ff48d041c4342a3aa6298da7af8c). In this commit I implemented the many-to-many relationship between two models, and I also provided some basic frontend to test it.

**Comment by canguler** [comment]
Completed. You can see my review at the end of commit's page: https://github.com/bounswe/bounswe2015group5/commit/dcea5f680623ff48d041c4342a3aa6298da7af8c

I also added my review's link to Code Review Assignment page:
https://github.com/bounswe/bounswe2015group5/wiki/Code-Review-Assignment
