### ISSUE TITLE
Code Review Request

### ISSUE THREAD

**Issue by mehmetburakkurutmaz** [bounswe/bounswe2015group5#207]
I need some feedback on my [commit](https://github.com/bounswe/bounswe2015group5/commit/71b1bce7d2b4059e548cde7d6a5eb3ac85292e3e). In this commit I implemented a servlet that replies get and post methods with Contributions given UserID.

**Comment by abdullahanefi** [comment]
Provided my comments on the [commit page](https://github.com/bounswe/bounswe2015group5/commit/71b1bce7d2b4059e548cde7d6a5eb3ac85292e3e).

This code review session is documented on the wiki page
