### ISSUE TITLE
Make requested corrections based on @haknsahn 's code review

### ISSUE THREAD

**Issue by moguz** [bounswe/bounswe2015group5#210]
I will
* implement rate functionality in Contribution detail page
* make tags clickable, and put *TODO* comments until our Tag Page is implemented

**Comment by moguz** [comment]
Rate functionality in Contribution detail page is implemented with f46f783e0ef4493f4325a14b9d9134e68b84686c

**Comment by muratakif** [comment]
Provided some comments in the commit page.
