### ISSUE TITLE
Deploy war file to server

### ISSUE THREAD

**Issue by canguler** [bounswe/bounswe2015group5#221]
As you know, back-end code works on local, but when we deploy our `.war` file to Amazon server it doesn't. We need to solve this problem as soon as possible.

**Comment by abdullahanefi** [comment]
This issue is fixed. Thanks to the help of @bilalyasar and @hamzaozturk . You can do the following if necessary : 
 - Connect via ssh
 - git pull origin master
 - mvn package
 - copy the packaged war to tomcat directory in  /usr/share/

I recommend you contact me instead. I would gladly deploy it
