### ISSUE TITLE
Research on Basic Auth practices in AngularJS

### ISSUE THREAD

**Issue by abdullahanefi** [bounswe/bounswe2015group5#232]
This may be a good start : [AngularJS Basic HTTP Authentication Example](http://jasonwatmore.com/post/2014/05/26/AngularJS-Basic-HTTP-Authentication-Example.aspx)

**Comment by canguler** [comment]
Since "registration" functionality using "POST" request are @mehmetburakkurutmaz 's responsibility, he and @abdullahanefi should decide together on the authentication method.

**Comment by canguler** [comment]
As we've changed authentication system, this issue holds no more.
