### ISSUE TITLE
Tomcat problem -  no manager

### ISSUE THREAD

**Issue by abdullahanefi** [bounswe/bounswe2015group5#233]
The tomcat server is running but the main page of tomcat server and the manager is not available.

**Comment by hamzaozturk** [comment]
Sometimes, tomcat application deployment sytstem can delete manager directory located under webapps. If you do not have manager directory under webapps, download tomcat archive file again and move manager directory. Then, change autoDeploy value to false inside the file <tomcat-directory>/conf/server.xml.

**Comment by mrtcnnccn** [comment]
Thank you, it also solved my problem.

**Comment by abdullahanefi** [comment]
Thanks for your help Hamza. Glad it helped other groups as well
