### ISSUE TITLE
Empty page when connecting to app

### ISSUE THREAD

**Issue by uskudarli** [bounswe/bounswe2015group5#259]
I can not see any content when connecting to the app. I also can not login or create anything.

I presume there is a DB connection problem? Or some system crash?

**Comment by canguler** [comment]
I redeployed the war file from my smartphone and system started to work again. As I don't have a computer right now, I couldn't check our logs, crash reports etc.

@abdullahanefi, could you check the problem if it happens again.

**Comment by uskudarli** [comment]
Yep, working now. Thanks.

Just doing some final tests. 

When you discover why it stopped, I would like to know. 

Thanks.
